[x13]
type = sftp
host = 10.0.0.6
user = devu
pass = 091S5HODhxZmLS7iDzN5An1Cn_Fv_n8e
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[manj]
type = sftp
host = 10.0.0.70
pass = vBlxmz6hHohC1CxnEhTGdq6CcxDJuQgz
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[lapp]
type = sftp
host = 10.0.0.79
pass = FBh360wTLDTomr3hrcOZXNGSlYjAEIF5
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

