#!/usr/bin/env bash

*
!$HOME/.gtkrc-2.0
!$HOME/.xinitrc
!$HOME/.Xresources
!$HOME/.zshenv
!$HOME/1mon.sh
!$HOME/2mon.sh
!$HOME/.config/alacritty/alacritty.toml
!$HOME/.config/alacritty/print_colors.sh
!$HOME/.config/background/firewatch-dark-minimal-5k-58.png
!$HOME/.config/btop/**
!$HOME/.config/dunst/dunstrc
!$HOME/.config/galculator/galculator.conf
!$HOME/.config/gtk-3.0/settings.ini
!$HOME/.config/i3/config
!$HOME/.config/Kvantum/kvantum.kvconfig
!$HOME/.config/micro/bindings.json
!$HOME/.config/micro/settings.json
!$HOME/.config/mpv/mpv.conf
!$HOME/.config/neofetch/config.conf
!$HOME/.config/networkmanager-dmenu/config.ini
!$HOME/.config/polybar/**
!$HOME/.config/qt5ct/qt5ct.conf
!$HOME/.config/ranger/rc.conf
!$HOME/.config/arkrc
!$HOME/.config/dolphinrc
!$HOME/.config/gwenviewrc
!$HOME/.config/katerc
!$HOME/.config/kwalletrc
!$HOME/.config/mimeapps.list
!$HOME/.local/share/kxmlgui5/**
